### ISSUE TITLE
Size metrics build.sh calls for codecoverage src path internally

### ISSUE THREAD

**Issue by Firdouss786** [SonarSource/sonar-training-examples#62]
Hi SonarTrainingTeam,

build.sh is referring to "testFile="src/test/java/coverage_metrics/CoverageMetricsTest.java"" but it is suppose to refer to "src/test/java/size_metrics/SizeMetricsTest.java"

It was poping error while runing through jenkins, kindly rectify.

**Comment by okorach** [comment]
Fixed
