### ISSUE TITLE
Failed to analyze example project portfolios\tier2-biz-logic

### ISSUE THREAD

**Issue by CaoFeng1226** [SonarSource/sonar-training-examples#74]
Error message:

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project sonar-ldap: Not inside a Git work tree : D:\sonar-training-examples-master\portfolios\tier2-biz-logic\sonar-ldap -> [Help 1]`

**Comment by okorach** [comment]
Verified today. It works OK as long as you clone the repo
